-- ============================================================================
-- Kenshi Overhaul Suite -- CAPABILITY PROBE RUNNER
--
-- Consumes probe_manifest.lua (generated by tools/gen_probes.py) and produces a
-- VERIFIED capability matrix: which documented bindings actually work on a live
-- game, which are broken, and which are absent.
--
-- The bindings doc is auto-generated from C++ headers and has never been
-- executed -- this is what converts "the docs claim" into "we tested".
--
-- SAFETY:
--   * Only calls zero-arg read-verb methods that survived the generator's
--     blocklist (no _DESTRUCTOR / kill / set* / save* ... ).
--   * Reads fields; NEVER writes one.
--   * Every call is pcall-wrapped; a broken binding logs and moves on.
--   * Touches no game state. Safe to run on a live save.
--
-- RUN: Ctrl+Shift+L -> Script Editor -> load this -> Run. Results in Logger,
--      and written to probe_results.txt next to the script if io is available.
-- ============================================================================

local TAG = "[SUITE-CAP] "
local function log(m) print(TAG .. tostring(m)) end

-- ---------------------------------------------------------------------------
-- Load the generated manifest. It sits beside this script.
-- ---------------------------------------------------------------------------
local manifest
do
    local candidates = {
        "probe_manifest",                       -- if package.path covers us
        "mods/KenshiLua/scripts/probe_manifest", -- deployed location
    }
    for _, mod in ipairs(candidates) do
        local ok, res = pcall(require, mod)
        if ok and type(res) == "table" then manifest = res break end
    end
    if not manifest then
        -- fall back to dofile against the deployed path
        local ok, res = pcall(dofile, "mods/KenshiLua/scripts/probe_manifest.lua")
        if ok and type(res) == "table" then manifest = res end
    end
end

if not manifest then
    log("FATAL: could not load probe_manifest.lua -- is it deployed next to this script?")
    return
end

local nclass = 0
for _ in pairs(manifest) do nclass = nclass + 1 end
log("manifest loaded: " .. nclass .. " classes")

-- ---------------------------------------------------------------------------
-- Gather SPECIMENS: live objects to probe, tagged with their documented class.
-- We can only test a class if we can obtain an instance of it.
-- ---------------------------------------------------------------------------
local specimens = {}
local function addSpecimen(className, obj, how)
    if obj ~= nil then
        specimens[#specimens + 1] = { cls = className, obj = obj, how = how }
    end
end

local function tryGlobal(name)
    local fn = _G[name]
    if type(fn) ~= "function" then return nil end
    local ok, res = pcall(fn)
    if ok then return res end
    return nil
end

-- GameWorld: confirmed reachable (printed as "kenshilua.gameworld object")
local world = tryGlobal("getGameWorld")
addSpecimen("GameWorld", world, "getGameWorld()")

-- PlayerInterface: owns getAnyPlayerCharacter / getAllPlayerCharacters
local player = tryGlobal("getPlayerInterface") or tryGlobal("getPlayer")
addSpecimen("PlayerInterface", player, "getPlayerInterface()")

-- A live Character, then everything hanging off it.
local character
if player then
    local ok, c = pcall(function() return player:getAnyPlayerCharacter() end)
    if ok then character = c end
end
addSpecimen("Character", character, "player:getAnyPlayerCharacter()")

if character then
    local ok, stats = pcall(function() return character:getStats() end)
    if ok then addSpecimen("CharStats", stats, "character:getStats()") end

    local okI, inv = pcall(function() return character:getInventory() end)
    if okI then addSpecimen("Inventory", inv, "character:getInventory()") end

    local okM, mv = pcall(function() return character:getMovement() end)
    if okM then addSpecimen("CharMovement", mv, "character:getMovement()") end

    local okF, fac = pcall(function() return character:getFaction() end)
    if okF then addSpecimen("Faction", fac, "character:getFaction()") end
end

log("specimens gathered: " .. #specimens)
for _, s in ipairs(specimens) do
    log("  " .. s.cls .. "  via " .. s.how .. "  -> " .. tostring(s.obj))
end

-- ---------------------------------------------------------------------------
-- PROBE. For each specimen, exercise its class's safe methods + fields.
-- ---------------------------------------------------------------------------
local results = {}   -- lines for the report
local tally = { ok = 0, err = 0, nilret = 0, missing = 0, fields_ok = 0, fields_err = 0 }

local function record(line) results[#results + 1] = line end

for _, s in ipairs(specimens) do
    local entry = manifest[s.cls]
    if not entry then
        log("no manifest entry for class " .. s.cls)
    else
        record("")
        record("== " .. s.cls .. "  (" .. s.how .. ") ==")

        -- methods: zero-arg readers only
        for _, m in ipairs(entry.methods or {}) do
            local fn = s.obj[m.name]
            if fn == nil then
                tally.missing = tally.missing + 1
                record(("  ABSENT   %s()  [doc says -> %s]"):format(m.name, m.ret))
            else
                local ok, res = pcall(function() return s.obj[m.name](s.obj) end)
                if not ok then
                    tally.err = tally.err + 1
                    record(("  BROKEN   %s()  err=%s"):format(m.name, tostring(res)))
                elseif res == nil then
                    tally.nilret = tally.nilret + 1
                    record(("  NIL      %s()  [doc says -> %s]"):format(m.name, m.ret))
                else
                    tally.ok = tally.ok + 1
                    record(("  OK       %s() = %s"):format(m.name, tostring(res)))
                end
            end
        end

        -- fields: READ ONLY, never write
        for _, f in ipairs(entry.fields or {}) do
            local ok, res = pcall(function() return s.obj[f.name] end)
            if not ok then
                tally.fields_err = tally.fields_err + 1
                record(("  F-BROKEN %s  err=%s"):format(f.name, tostring(res)))
            else
                tally.fields_ok = tally.fields_ok + 1
                record(("  F-OK     %s (%s %s) = %s"):format(f.name, f.ty, f.rw, tostring(res)))
            end
        end
    end
end

-- ---------------------------------------------------------------------------
-- SUMMARY
-- ---------------------------------------------------------------------------
log("================ CAPABILITY SUMMARY ================")
log(("methods  OK=%d  NIL=%d  BROKEN=%d  ABSENT=%d"):format(
    tally.ok, tally.nilret, tally.err, tally.missing))
log(("fields   OK=%d  BROKEN=%d"):format(tally.fields_ok, tally.fields_err))
log("====================================================")

-- Write the full matrix to a file if LuaJIT's io is available.
local wrote = false
if io and io.open then
    local paths = {
        "mods/KenshiLua/scripts/probe_results.txt",
        "probe_results.txt",
    }
    for _, p in ipairs(paths) do
        local fh = io.open(p, "w")
        if fh then
            fh:write("Kenshi Overhaul Suite -- verified capability matrix\n")
            fh:write(("methods OK=%d NIL=%d BROKEN=%d ABSENT=%d | fields OK=%d BROKEN=%d\n"):format(
                tally.ok, tally.nilret, tally.err, tally.missing, tally.fields_ok, tally.fields_err))
            fh:write(table.concat(results, "\n"))
            fh:write("\n")
            fh:close()
            log("wrote " .. p)
            wrote = true
            break
        end
    end
end
if not wrote then
    log("io unavailable -- dumping matrix to log instead:")
    for _, l in ipairs(results) do log(l) end
end
